### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by berkus** [probe-rs/log-viewer#2]
Compiling with stable toolchain and empty GH_TOKEN I get this on startup:

```
env GH_TOKEN= cargo run -- probe.log
   Compiling log-viewer v0.1.0 (/Users/berkus/log-viewer)
    Finished dev [unoptimized + debuginfo] target(s) in 1.24s
     Running `target/debug/log-viewer probe.log`
thread 'main' panicked at /Users/berkus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/js-sys-0.3.60/src/lib.rs:5520:9:
cannot call wasm-bindgen imported functions on non-wasm targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Yatekii** [comment]
Ah, sorry, the README never saw the necessary love ... so you need to use [trunk](https://trunkrs.dev/). You can install it and then it should be as simple as `trunk watch` :)

Also, the log viewer has a bug currently where it does not receive the full content from the GH gist API. I never managed to find a proper solution.

**Comment by Tiwalun** [comment]
I've updated the README, and the deployed version at <http://logs.probe.rs> is now functional again.
